let str="javascript"
let str1=" language widely known  "
console.log(str.length)//to get the length of string
//console.log(str.concat("s"))
//console.log(str.concat(str1))//to concatinate two strings
//console.log(str.charAt(3))//returns the element at specified index
// console.log(str.endsWith('t'))
//  console.log(str.includes("d"))
//  console.log(str.indexOf("s"))
// console.log(str.lastIndexOf("a"))
// console.log(str.localeCompare())
// console.log(str.replace('a',"A"))
// console.log(str.replaceAll('a',"A"))
//console.log(str.repeat(2))
// console.log(str.startsWith('j'))
// console.log(str.toLowerCase())
// console.log(str.toUpperCase())
// console.log(str1.split(" "))
// console.log(str.toString())
// console.log(str.valueOf())
// console.log(str.toLocaleLowerCase())
// console.log(str1.toLocaleUpperCase())
// console.log(str.match("t"))
//  console.log(str1.replaceAll('a','A'))
// //console.log(str1.trim())
// //console.log(str1.trimStart())
// //console.log(str1.trimEnd())
// //console.log(str.matchAll("t"))
// console.log(str)
// console.log(str.padStart(16,"xy"))
// console.log(str.padEnd(16,"language"))
// console.log(str.search('a'))
// console.log(str.slice(1,5))
// console.log(str.substring(1,5))
console.log(str.codePointAt(5))

console.log(str)
